apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a3940)
  labels:
    io.kompose.service: chat-service
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chat-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a3940)
      labels:
        io.kompose.service: chat-service
    spec:
      containers:
        - env:
            - name: ACCESS_TOKEN_SECRET
              value: 75a09b812d16c5c9bdadfce8fb6daa032a0ffb4046857c8c505fd7f739630ac4bb7f79749d52e9de1e43465925d812498dccbfce9252aa12db2103fe4e7c1af
            - name: AUTH_SERVICE_URL
              value: http://auth-service:3000
            - name: CORS_ORIGIN
              value: http://localhost:3001
            - name: DB_SERVICE_URL
              value: http://db-service:4000
            - name: DISABLE_RATE_LIMIT
              value: "true"
            - name: MONGODB_URI
              value: mongodb://admin:password@mongodb:27017/chat_service?authSource=admin
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "5000"
          image: chat-service
          livenessProbe:
            exec:
              command:
                - wget
                - --no-verbose
                - --tries=1
                - --spider
                - http://localhost:5000/health
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: todo-chat-service
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
